server:
    http_listen_port: ${PORT:-9080}
    grpc_listen_port: ${GRPC_PORT:-10080}

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://${LOKI_TENANT_ID}:${LOKI_TOKEN}@${LOKI_HOST}/loki/api/v1/push

scrape_configs:
  - job_name: ${JOB_NAME:-render}
    syslog:
      listen_address: 0.0.0.0:${SYSLOG_PORT:-1514}
      label_structured_data: true
      labels:
        job: syslog