server:
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://${LOKI_TENANT_ID}:${LOKI_TOKEN}@${LOKI_HOST}/loki/api/v1/push

scrape_configs:
  - job_name: ${JOB_NAME:-render}
    syslog:
      listen_address: 0.0.0.0:${PORT}
      label_structured_data: yes
      use_incoming_timestamp: yes
      labels:
        job: syslog

