server:
    http_listen_port: ${PORT:-9080}
    grpc_listen_port: ${GRPC_PORT:-10080}

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://${LOKI_TENANT_ID}:${LOKI_TOKEN}@${LOKI_HOST}/loki/api/v1/push

scrape_configs:
  - job_name: ${JOB_NAME:-render}
    syslog:
      listen_address: 0.0.0.0:${SYSLOG_PORT:-1514}
      idle_timeout: 10m
      labels:
        job: syslog
    relabel_configs:
    - source_labels: ['__syslog_message_hostname']
      target_label: 'host'
    - source_labels: ['__syslog_message_severity']
      target_label: 'severity'
    - source_labels: ['__syslog_message_appname']
      target_label: 'app'
    - source_labels: ['__syslog_message_msgId']
      target_label: 'process'